/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import GUI.Mesa;
import sockets.GameState;
import sockets.Servidor;

/**
 *
 * @author Manuel Arias & Justin Bogantes
 * @since 16/10/18
 */
public class Empezar extends javax.swing.JFrame {

    /**
     * Creates new form Empezar
     */
    public Empezar() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gifCartas = new javax.swing.JLabel();
        gifVerde = new javax.swing.JLabel();
        gifRojo1 = new javax.swing.JLabel();
        gifRojo2 = new javax.swing.JLabel();
        textoEsperar = new javax.swing.JLabel();
        avanzarAMesa = new javax.swing.JButton();
        fondoNegro = new javax.swing.JLabel();

        jLabel2.setText(" ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gifCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/juego-de-cartas-y-naipe-imagen-animada-0071.gif"))); // NOI18N
        jPanel1.add(gifCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 260, 200));

        gifVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-verde.gif"))); // NOI18N
        jPanel1.add(gifVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        if (GameState.cantJugadores == 2){
            gifRojo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-verde.gif"))); // NOI18N
        } else {
            gifRojo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-rojo.gif")));
        }
        jPanel1.add(gifRojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        if ((GameState.cantJugadores) == 3){
            gifRojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-verde.gif"))); // NOI18N
        }else{
            gifRojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-rojo.gif")));
        }
        jPanel1.add(gifRojo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        textoEsperar.setBackground(new java.awt.Color(255, 255, 255));
        textoEsperar.setFont(new java.awt.Font("Curlz MT", 3, 36)); // NOI18N
        textoEsperar.setForeground(new java.awt.Color(255, 255, 255));
        textoEsperar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEsperar.setText("Esperando por otros jugadores . . .");
        jPanel1.add(textoEsperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 50));

        avanzarAMesa.setText("Avanzar a la mesa");
        avanzarAMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarAMesaActionPerformed(evt);
            }
        });
        jPanel1.add(avanzarAMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 20, 140, 40));

        fondoNegro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/fondo2.jpg"))); // NOI18N
        jPanel1.add(fondoNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avanzarAMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarAMesaActionPerformed
        Mesa obj = new Mesa();
        obj.setVisible(true);
        dispose();
        
        Servidor.repartirCartasIniciales();
    }//GEN-LAST:event_avanzarAMesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empezar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avanzarAMesa;
    private javax.swing.JLabel fondoNegro;
    private javax.swing.JLabel gifCartas;
    private javax.swing.JLabel gifRojo1;
    private javax.swing.JLabel gifRojo2;
    private javax.swing.JLabel gifVerde;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoEsperar;
    // End of variables declaration//GEN-END:variables
}
