/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Mesa;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sockets.GameState;
import sockets.Servidor;

/**
 *
 * @author Manuel Arias & Justin Bogantes
 * @since 16/10/18
 */
public class Espera extends javax.swing.JFrame {

    /**
     * Creates new form Empezar
     */
    public Espera() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gifCartas = new javax.swing.JLabel();
        gifRojo = new javax.swing.JLabel();
        gifRojo2 = new javax.swing.JLabel();
        gifRojo3 = new javax.swing.JLabel();
        textoEsperar = new javax.swing.JLabel();
        fondoNegro = new javax.swing.JLabel();

        jLabel2.setText(" ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gifCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/juego-de-cartas-y-naipe-imagen-animada-0071.gif"))); // NOI18N
        jPanel1.add(gifCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 260, 200));

        gifRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-rojo.gif"))); // NOI18N
        jPanel1.add(gifRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        if (GameState.cantJugadores == 2){
            gifRojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-rojo.gif"))); // NOI18N
        } else {
            gifRojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-rojo.gif")));
        }
        jPanel1.add(gifRojo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        if ((GameState.cantJugadores) == 3){
            gifRojo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-rojo.gif"))); // NOI18N
        }else{
            gifRojo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/loading-rojo.gif")));
        }
        jPanel1.add(gifRojo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        textoEsperar.setBackground(new java.awt.Color(255, 255, 255));
        textoEsperar.setFont(new java.awt.Font("Curlz MT", 3, 36)); // NOI18N
        textoEsperar.setForeground(new java.awt.Color(255, 255, 255));
        textoEsperar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEsperar.setText("Esperando por otros jugadores . . .");
        jPanel1.add(textoEsperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 50));

        fondoNegro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/fondo2.jpg"))); // NOI18N
        jPanel1.add(fondoNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Espera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Espera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Espera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Espera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Espera().setVisible(true);
            }
        });
    }
    
    public void Update(int numeroJugadores) {
        if (numeroJugadores == 2) {
            LoadJugador2();
        } else {
            LoadJugador3();
        }
    }
    
    public void Load(int jugador){
        switch (jugador) {
            case 1:
                LoadJugador();
                break;
            case 2:
                LoadJugador2();
                break;
            case 3:
                LoadJugador3();
                break;
        }
    }
    
    public void LoadJugador(){
        ImageIcon foto = new ImageIcon("scr/Multimedia/loading-rojo.gif");
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        gifRojo.setIcon(icono);
    }
    
    public void LoadJugador2(){
        ImageIcon foto = new ImageIcon("scr/Multimedia/loading-rojo.gif");
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        gifRojo.setIcon(icono);
        gifRojo2.setIcon(icono);
    }
    
    public void LoadJugador3(){
        ImageIcon foto = new ImageIcon("scr/Multimedia/loading-rojo.gif");
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        gifRojo.setIcon(icono);
        gifRojo2.setIcon(icono);
        gifRojo3.setIcon(icono);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoNegro;
    private javax.swing.JLabel gifCartas;
    private javax.swing.JLabel gifRojo;
    private javax.swing.JLabel gifRojo2;
    private javax.swing.JLabel gifRojo3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoEsperar;
    // End of variables declaration//GEN-END:variables
}
